# - Numpy Practice

In [1]:
# import libraries

import numpy as np

## - Creating 1D Array

In [2]:
food= np.array(["pakora" , "samosa" , "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
# create 1D aaray

arr= np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

### - Different functions of 1D array

In [4]:
type(food)

numpy.ndarray

In [5]:
len(food)

3

In [6]:
# to get a specific element on index

food[2]

'raita'

In [7]:
food[0:]

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [8]:
food[1:]

array(['samosa', 'raita'], dtype='<U6')

In [9]:
prices = np.array([5,10,20])
prices

array([ 5, 10, 20])

In [10]:
prices.mean()

11.666666666666666

In [11]:
zro= np.zeros(5)
zro

array([0., 0., 0., 0., 0.])

In [12]:
ons=np.ones(4)
ons

array([1., 1., 1., 1.])

In [13]:

np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [15]:
# table of 5 through range function

np.arange(5 ,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
# Line space function, the 3rd values "5" indicates that we want ONLY 5 Values/intervals to show 1-10

np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
# Specify data type

np.ones(5 , dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [18]:
# Specify data type

np.ones(5 , dtype=np.float64)

array([1., 1., 1., 1., 1.])

In [19]:
# Specify data type

np.ones(5 , dtype=np.float)

C:\Users\AhmadLap\AppData\Local\Temp\ipykernel_7632\3461763384.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones(5 , dtype=np.float)


array([1., 1., 1., 1., 1.])

## - Array Functions

In [20]:
a= np.array([10,30,5,4,0.5,1])
a

array([10. , 30. ,  5. ,  4. ,  0.5,  1. ])

In [21]:
# array sorting

a.sort()
a

array([ 0.5,  1. ,  4. ,  5. , 10. , 30. ])

In [22]:
# make another array

b=np.array([8,70,3,1.5,5.6])
b

array([ 8. , 70. ,  3. ,  1.5,  5.6])

In [23]:
# concatenate array a and b

c=np.concatenate((a,b))
c

array([ 0.5,  1. ,  4. ,  5. , 10. , 30. ,  8. , 70. ,  3. ,  1.5,  5.6])

In [24]:
# sort after concatintaion

c.sort()
c

array([ 0.5,  1. ,  1.5,  3. ,  4. ,  5. ,  5.6,  8. , 10. , 30. , 70. ])

##     - Creating 2D Array

In [25]:
array2 = np.ones((3,4))
array2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
a= np.array([ [1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [27]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [28]:
# lets concatenate a and b array 

np.concatenate((a,b),axis=0)  #if we dont set axis 0 here, it still bydefault will show same result

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
# concatenate with specific axis

np.concatenate((a,b) , axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## - 3D Arrays

In [30]:
# for 3d array, just put 2-d array multiple times, 

a=np.array([[[1,2],[3,4]] , [[5,6],[7,8]], [[9,10],[11,12]] ])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [31]:
# lets check its dimention

a.ndim


3

## - 3D array also called Tensor, or 3D array

In [32]:
# lets do some trick and find out what dimention array is it

b= np.array([[5,6,7],[8,9,10],[2,3,4]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 2,  3,  4]])

In [33]:
b.ndim

2

In [34]:
# to check size(number of elements) of array

b.size

9

In [35]:
# printing "a" again, to check its shape

a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [36]:
a.shape

(3, 2, 2)

In [37]:
# above result mean "3" is the set of 2D arrays, 2 is nmber of rows and last 2 is colms

In [38]:
# create a 1D array and convert into 2D atrray, into rows and colms

a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
a.ndim

1

In [40]:
# so above I have total 9 elements in array, in order to convert it into rows and colms(2D) I've to do it 3*3

b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
b.ndim

2

In [42]:
# one other method to reshape

np.reshape(a, newshape=(1,9) ,order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [43]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a*6

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])

In [45]:
# it will add "2" to each element of the array a

a+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
# it will add up all elements of array

a.sum()

45

In [47]:
a.mean()

4.5