In [1]:
import numpy as np

my_arry = np.array([3,6,8,2])
my_arry

array([3, 6, 8, 2])

In [2]:
type(my_arry)

numpy.ndarray

In [3]:
my_arry[1]

6

In [4]:
my_arry[0:]

array([3, 6, 8, 2])

In [5]:
my_arry[1:]

array([6, 8, 2])

In [6]:
len(my_arry)

4

## - 2D Array/ Matrix

In [7]:
mtrx= np.array([[5,5,5,5],[5,5,5,5],[5,5,5,5],[5,5,5,5]])
mtrx

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [8]:
type(mtrx)

numpy.ndarray

In [9]:
len(mtrx)

4

## - How to create array

In [10]:
import numpy as np
arr= np.ones(3)
arr

array([1., 1., 1.])

In [11]:
zeros_arr = np.zeros(3)
zeros_arr

array([0., 0., 0.])

In [12]:
empty_arr = np.empty(3)
empty_arr

array([0., 0., 0.])

## - array with range function

In [13]:
rng_arr = np.arange(6)
rng_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
# array with range limit

lmt_rang_arr = np.arange(2,8)
lmt_rang_arr

array([2, 3, 4, 5, 6, 7])

In [15]:
# range array with specific condition or interval

ary= np.arange(2,20, 2)
ary

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# linerly spaced array

liner_arr = np.linspace(0,10,num=5)
liner_arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [17]:
zro_matrx= np.zeros((4,5))
zro_matrx

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
m = np.ones((5,7))
m

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## - 3D Array

In [19]:
# Making and reshaping 3D Array

ar= np.arange(24).reshape(2,3,4)
ar

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])